### ISSUE TITLE
SyntaxError: syntax error at or near "JOIN"

### ISSUE THREAD

**Issue by ksagar8848** [8848digital/india_compliance#10]
### Information about bug

 test_validate_e_invoice_applicable_companies_without_applicable_from (india_compliance.gst_india.doctype.gst_settings.test_gst_settings.TestGSTSettings.test_validate_e_invoice_applicable_companies_without_applicable_from)

### Version

Frappe-v-15
ErpNext-v-15

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 80, in inner
    with self._recreate_cm():
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/tests/utils.py", line 320, in change_settings
    settings.save(ignore_permissions=True)
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 342, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 378, in _save
    self.run_before_save_methods()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_settings/gst_settings.py", line 48, in validate
    self.update_e_invoice_status()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_settings/gst_settings.py", line 71, in update_e_invoice_status
    frappe.enqueue(update_e_invoice_status, queue="long", timeout=6000)
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/__init__.py", line 2263, in enqueue
    return frappe.utils.background_jobs.enqueue(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 118, in enqueue
    return frappe.call(method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_settings/gst_settings.py", line 419, in update_e_invoice_status
    update_pending_status(e_invoice_applicability_date)
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gst_settings/gst_settings.py", line 483, in update_pending_status
    query.run()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "JOIN"
LINE 1: UPDATE "tabSales Invoice" JOIN "tabSales Invoice Item" ON "t...
                                  ^
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pallavi238848** [comment]
@tinadn , can you check the fix is done or not, if yes we can any consultant to check and close.

**Comment by swathibollineni2** [comment]
@ksagar8848 test_validate_e_invoice_applicable_companies_without_applicable_from  - passed
