### ISSUE TITLE
psycopg2.errors.GroupingError: column "tabPurchase Invoice.name" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by ksagar8848** [8848digital/india_compliance#15]
### Information about bug

test_gstr_3b_report (india_compliance.gst_india.doctype.gstr_3b_report.test_gstr_3b_report.TestGSTR3BReport.test_gstr_3b_report)

### Version

ERPNext: v15.46.1 (pre-prod)
Frappe Framework: v15.50.1 (pre-prod)
India Compliance: v15.14.5 (pre-prod)

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/test_gstr_3b_report.py", line 64, in test_gstr_3b_report
    ).insert()
      ^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in insert
    self.run_before_save_methods()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 36, in validate
    self.get_data()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 83, in get_data
    raise e
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 57, in get_data
    self.get_itc_reversal_entries()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 123, in get_itc_reversal_entries
    self.update_itc_reversal_from_purchase_invoice()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 127, in update_itc_reversal_from_purchase_invoice
    self.update_itc_reversal_for_purchase_us_17_4()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 148, in update_itc_reversal_for_purchase_us_17_4
    ).get_for_purchase(
      ^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/report/gstr_3b_details/gstr_3b_details.py", line 454, in get_for_purchase
    return query.groupby(dt[group_by]).run(as_dict=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabPurchase Invoice.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT 'Purchase Invoice' "voucher_type","tabPurchase Invoic...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tinadn** [comment]
Resolved. Hence closing.
