### ISSUE TITLE
Server error while creating an invoice

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/india_compliance#2]
### Information about bug

Server error while creating an invoice

![image](https://github.com/user-attachments/assets/c0e3d98d-0907-4d10-824d-a988205dd869)

### Version

.

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"apnaklub_mobile_app": "0.0.1",
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.36.2",
	"frappe": "15.41.0",
	"india_compliance": "15.14.2",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-mrktnfblds
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 235, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/selling_controller.py", line 29, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 52, in validate
    super().validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 265, in validate
    apply_pricing_rule_on_transaction(self)
  File "apps/erpnext/erpnext/accounts/doctype/pricing_rule/utils.py", line 554, in apply_pricing_rule_on_transaction
    pricing_rules = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column tabPricing Rule.campaign does not exist
LINE 2: ..."tabPricing Rule".supplier, '') = '' and coalesce("tabPricin...
                                                             ^


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Sales Invoice\",\"name\":\"new-sales-invoice-mrktnfblds\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"SINV-.YY.-\",\"e_waybill_status\":\"\",\"company\":\"_Test Indian Registered Company\",\"posting_date\":\"2024-12-05\",\"set_posting_time\":0,\"is_pos\":0,\"is_consolidated\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_sales_order\":0,\"update_billed_amount_in_delivery_note\":1,\"is_debit_note\":0,\"is_reverse_charge\":0,\"is_export_with_gst\":0,\"currency\":\"INR\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"update_stock\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Sales Invoice Item\",\"name\":\"new-sales-invoice-item-gjpqlsstko\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"has_item_scanned\":0,\"item_group\":\"Mobile Accessories\",\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"grant_commission\":1,\"delivered_by_supplier\":0,\"is_fixed_asset\":0,\"enable_deferred_revenue\":0,\"use_serial_batch_fields\":1,\"allow_zero_valuation_rate\":0,\"cost_center\":\"Main - _TIRC\",\"page_break\":0,\"parent\":\"new-sales-invoice-mrktnfblds\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"qty\":1,\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":100,\"amount\":100,\"base_rate\":100,\"base_amount\":100,\"stock_uom_rate\":100,\"net_rate\":100,\"net_amount\":100,\"base_net_rate\":100,\"base_net_amount\":100,\"taxable_value\":0,\"igst_rate\":0,\"cgst_rate\":0,\"sgst_rate\":0,\"cess_rate\":0,\"cess_non_advol_rate\":0,\"igst_amount\":0,\"cgst_amount\":0,\"sgst_amount\":0,\"cess_amount\":0,\"cess_non_advol_amount\":0,\"weight_per_unit\":0,\"total_weight\":0,\"incoming_rate\":0,\"actual_batch_qty\":0,\"actual_qty\":0,\"delivered_qty\":0,\"gst_hsn_code\":\"25083010\",\"item_code\":\"OP-AC-001\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"OPPO Bluetooth Earbuds\",\"description\":\"True wireless earbuds with active noise cancellation and 24-hour battery life.\",\"image\":\"\",\"warehouse\":null,\"income_account\":\"Sales - _TIRC\",\"expense_account\":\"Cost of Goods Sold - _TIRC\",\"discount_account\":null,\"provisional_expense_account\":null,\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"update_stock\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2024-12-05\",\"against_blanket_order\":null,\"bom_no\":null,\"brand\":\"OPPO\",\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"customer_item_code\":null,\"has_margin\":false,\"free_item_data\":[],\"child_docname\":\"new-sales-invoice-item-gjpqlsstko\"}],\"taxes\":[{\"docstatus\":0,\"doctype\":\"Sales Taxes and Charges\",\"name\":\"new-sales-taxes-and-charges-yjzyhlmimq\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"cost_center\":\"Main - _TIRC\",\"account_currency\":null,\"dont_recompute_tax\":0,\"parent\":\"new-sales-invoice-mrktnfblds\",\"parentfield\":\"taxes\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"row_id\":null,\"account_head\":\"Output Tax IGST - _TIRC\",\"description\":\"IGST\",\"rate\":18,\"gst_tax_type\":null,\"tax_amount\":18,\"total\":118,\"tax_amount_after_discount_amount\":18,\"base_tax_amount\":18,\"base_total\":118,\"base_tax_amount_after_discount_amount\":18,\"item_wise_tax_detail\":\"{\\\"OP-AC-001\\\":[18,18]}\"}],\"use_company_roundoff_cost_center\":0,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"is_cash_or_non_trade_discount\":0,\"pricing_rules\":[],\"packed_items\":[],\"timesheets\":[],\"total_billing_amount\":0,\"payments\":[],\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"advances\":[],\"write_off_outstanding_amount_automatically\":0,\"redeem_loyalty_points\":0,\"territory\":\"All Territories\",\"ignore_default_payment_terms_template\":0,\"payment_schedule\":[],\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"group_same_items\":0,\"invoice_copy\":\"Original for Recipient\",\"mode_of_transport\":\"Road\",\"lr_date\":\"2024-12-05\",\"gst_vehicle_type\":\"Regular\",\"status\":\"Draft\",\"einvoice_status\":\"\",\"customer_group\":\"Corporate\",\"is_internal_customer\":0,\"is_discounted\":0,\"plc_conversion_rate\":1,\"total_billing_hours\":0,\"company_tax_id\":null,\"company_address\":\"_Test Indian Registered Company-Billing\",\"conversion_rate\":1,\"company_gstin\":\"24AAQCA8719H1ZC\",\"company_address_display\":\"Test Address - 1<br>Test City<br>\\nGujarat, State Code: 24<br>PIN Code: 380015<br>India<br>\\nGSTIN: 24AAQCA8719H1ZC<br>\",\"base_net_total\":100,\"net_total\":100,\"base_total\":100,\"total\":100,\"total_qty\":1,\"rounding_adjustment\":0,\"grand_total\":118,\"base_grand_total\":118,\"total_taxes_and_charges\":18,\"base_total_taxes_and_charges\":18,\"base_rounding_adjustment\":0,\"rounded_total\":118,\"base_rounded_total\":118,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"total_advance\":0,\"write_off_amount\":0,\"paid_amount\":0,\"base_paid_amount\":0,\"change_amount\":0,\"base_change_amount\":0,\"outstanding_amount\":118,\"posting_time\":\"17:10:17\",\"tax_id\":null,\"customer_name\":\"TechBridge Solutions\",\"loyalty_program\":null,\"represents_company\":null,\"customer\":\"C00025\",\"debit_to\":\"Debtors - _TIRC\",\"due_date\":\"2024-12-05\",\"customer_address\":\"TechBridge Solutions - Andheri West-Billing\",\"billing_address_gstin\":null,\"gst_category\":\"Unregistered\",\"address_display\":\"60, TechBridge Complex, Andheri West<br>Mumbai<br>\\nMaharashtra, State Code: 27<br>PIN Code: 400058<br>India<br>\\n\",\"shipping_address_name\":\"TechBridge Solutions - Andheri West-Billing\",\"shipping_address\":\"60, TechBridge Complex, Andheri West<br>Mumbai<br>\\nMaharashtra, State Code: 27<br>PIN Code: 400058<br>India<br>\\n\",\"tax_category\":\"\",\"place_of_supply\":\"27-Maharashtra\",\"taxes_and_charges\":\"Output GST Out-state - _TIRC\",\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"language\":\"en\",\"payment_terms_template\":null,\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery370047873773802970291": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 6661,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn tabPricing Rule.campaign does not exist\\nLINE 2: ...\\\"tabPricing Rule\\\".supplier, '') = '' and coalesce(\\\"tabPricin...\\n                                                             ^\\n\"]"
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tinadn** [comment]
Resolved. Hence closing.
