### ISSUE TITLE
GSTR -1 onload issue

### ISSUE THREAD

**Issue by tinadn** [8848digital/india_compliance#28]
### Information about bug

When trying to open GSTR-1 report Getting sql error

### Version

Frappe v-15
Erpnext v-15

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.47.1",
	"frappe": "15.51.0",
	"india_compliance": "15.14.6",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
query-report/GSTR-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 50, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 879, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 224, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 879, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 65, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 163, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 180, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/india_compliance/india_compliance/gst_india/report/gstr_1/gstr_1.py", line 53, in execute
    return Gstr1Report(filters).run()
  File "apps/india_compliance/india_compliance/gst_india/report/gstr_1/gstr_1.py", line 96, in run
    self.get_invoice_data()
  File "apps/india_compliance/india_compliance/gst_india/report/gstr_1/gstr_1.py", line 315, in get_invoice_data
    invoice_data = frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedColumn: column "Unregistered" does not exist
LINE 23:                     WHEN gst_category = "Unregistered" AND N...
                                                 ^


```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "GSTR-1",
		"filters": "{\"company\":\"PP Ltd\",\"from_date\":\"2024-11-01\",\"to_date\":\"2024-11-30\",\"type_of_business\":\"B2B\"}",
		"ignore_prepared_report": false,
		"are_default_filters": true
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedColumn",
	"_exc_source": "india_compliance (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"Unregistered\\\" does not exist\\nLINE 23:                     WHEN gst_category = \\\"Unregistered\\\" AND N...\\n                                                 ^\\n\"]"
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tinadn** [comment]
Duplicate issue.
