### ISSUE TITLE
frappe.exceptions.PermissionError

### ISSUE THREAD

**Issue by nirali8848** [8848digital/india_compliance#4]
### Information about bug

**Test Case Error**
ERROR: test_validate_transaction (india_compliance.gst_india.utils.test_e_waybill.TestEWaybill)

**Module**
india_compliance

### Version

Frappe -v15
ERPNEXT - v15

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/env/lib/python3.10/site-packages/responses/__init__.py", line 232, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/india_compliance/india_compliance/gst_india/utils/test_e_waybill.py", line 399, in test_validate_transaction
    si = self.create_sales_invoice_for("goods_item_with_ewaybill")
  File "/home/ubuntu/frappe-bench/apps/india_compliance/india_compliance/gst_india/utils/test_e_waybill.py", line 1022, in create_sales_invoice_for
    si = create_sales_invoice(**invoice_args, do_not_submit=True)
  File "/home/ubuntu/frappe-bench/apps/india_compliance/india_compliance/gst_india/utils/tests.py", line 9, in create_sales_invoice
    return create_transaction(**data)
  File "/home/ubuntu/frappe-bench/apps/india_compliance/india_compliance/gst_india/utils/tests.py", line 83, in create_transaction
    transaction.insert()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 284, in insert
    self.check_permission("create")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 220, in check_permission
    self.raise_no_permission_to(permtype)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 241, in raise_no_permission_to
    raise frappe.PermissionError
frappe.exceptions.PermissionError
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by pallavi238848** [comment]
@ksagar8848 , what is the status update on this?

**Comment by swathibollineni2** [comment]
@pallavi238848 , @ksagar8848 
test_validate_transaction  - ValidationError: Due Date cannot be before Posting / Supplier Invoice Date
