### ISSUE TITLE
Error while pulling advance paid for purchase invoice

### ISSUE THREAD

**Issue by Priya-Sonar** [8848digital/india_compliance#6]
### Information about bug

While pulling advance paid in purchase invoice it is giving error.
![Screenshot 2024-12-23 122220](https://github.com/user-attachments/assets/fb8dcf90-4920-4d84-9e1e-d2a335b46118)

### Version

ERPNext: v15.46.1 (pre-prod)

Frappe Framework: v15.50.1 (pre-prod)

India Compliance: v15.14.5 (pre-prod)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aasif-patel** [comment]
@Priya-Sonar please add the traceback with this type of error, in the error msg you can see there is options to copy the full error details.

**Comment by Priya-Sonar** [comment]
### App Versions
```
{
	"assets": "0.0.1",
	"crm": "0.0.1",
	"erpnext": "15.46.1",
	"frappe": "15.50.1",
	"india_compliance": "15.14.5",
	"payments": "0.0.1",
	"projects": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Purchase Invoice/PINV-24-00022
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 50, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 332, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1177, in set_advances
    res = self.get_advance_entries(
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 1235, in get_advance_entries
    payment_entries = get_advance_payment_entries_for_regional(
  File "apps/erpnext/erpnext/__init__.py", line 149, in caller
    return frappe.get_attr(overrides[function_path][-1])(*args, **kwargs)
  File "apps/india_compliance/india_compliance/gst_india/overrides/payment_entry.py", line 345, in get_advance_payment_entries_for_regional
    payment_entries = get_advance_payment_entries(
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 2943, in get_advance_payment_entries
    unallocated = list(q.run(as_dict=True))
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: operator does not exist: character varying = boolean
LINE 1: ...tors - PP Ltd','Creditors - PP Ltd') OR ("paid_to"=true AND ...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"docs": "{\"name\":\"PINV-24-00022\",\"owner\":\"Administrator\",\"creation\":\"2024-12-23 17:37:43.178529\",\"modified\":\"2024-12-23 17:37:43.178529\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"Unicon\",\"naming_series\":\"PINV-.YY.-\",\"supplier\":\"Unicon\",\"supplier_name\":\"Unicon\",\"company\":\"PP Ltd\",\"posting_date\":\"2024-12-23\",\"posting_time\":\"17:37:43.201567\",\"set_posting_time\":0,\"due_date\":\"2024-12-23\",\"is_paid\":0,\"is_return\":0,\"update_outstanding_for_self\":1,\"update_billed_amount_in_purchase_order\":0,\"update_billed_amount_in_purchase_receipt\":1,\"apply_tds\":1,\"is_reverse_charge\":0,\"tax_withholding_category\":\"TDS - 194C - Company\",\"currency\":\"INR\",\"conversion_rate\":1,\"use_transaction_date_exchange_rate\":1,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"update_stock\":0,\"is_subcontracted\":0,\"total_qty\":4,\"total_net_weight\":0,\"base_total\":100000,\"base_net_total\":100000,\"total\":100000,\"net_total\":100000,\"tax_withholding_net_total\":100000,\"base_tax_withholding_net_total\":100000,\"tax_category\":\"\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":2000,\"base_total_taxes_and_charges\":-2000,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":2000,\"total_taxes_and_charges\":-2000,\"base_grand_total\":98000,\"base_rounding_adjustment\":0,\"base_rounded_total\":98000,\"base_in_words\":\"INR Ninety Eight Thousand only.\",\"grand_total\":98000,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":98000,\"in_words\":\"INR Ninety Eight Thousand only.\",\"total_advance\":0,\"outstanding_amount\":98000,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto;\\\">\\n\\t<table class=\\\"table table-bordered table-hover\\\">\\n\\t\\t<thead>\\n\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-left\\\">HSN/SAC</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Taxable Amount</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Payment to Contractors (Single / Aggregate)</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t</tr>\\n\\t\\t</thead>\\n\\t\\t<tbody>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>None</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t₹ 1,00,000.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 2,000.00\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t</tbody>\\n\\t</table>\\n</div>\",\"gst_breakup_table\":null,\"base_paid_amount\":0,\"paid_amount\":0,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"supplier_address\":\"Unicon-Billing\",\"address_display\":\"Karnataka<br>\\nKarnataka<br>\\nKarnataka<br>560102<br>India<br>\\n<br>\\n\",\"supplier_gstin\":\"29AAACH7409R1ZX\",\"gst_category\":\"Registered Regular\",\"shipping_address\":\"PP-MH-Billing\",\"shipping_address_display\":\"001<br>\\nFort<br>Mumbai<br>\\nMaharashtra<br>400001<br>India<br>\\n<br>\\n\",\"billing_address\":\"PP-MH-Billing\",\"billing_address_display\":\"001<br>\\nFort<br>Mumbai<br>\\nMaharashtra<br>400001<br>India<br>\\n<br>\\n\",\"place_of_supply\":\"29-Karnataka\",\"ignore_default_payment_terms_template\":0,\"status\":\"Draft\",\"per_received\":0,\"credit_to\":\"Creditors - PP Ltd\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"against_expense_account\":\"Stock Received But Not Billed - PP Ltd\",\"letter_head\":\"PP Ltd\",\"group_same_items\":0,\"language\":\"en\",\"distance\":0,\"mode_of_transport\":\"Road\",\"lr_date\":\"2024-12-23\",\"gst_vehicle_type\":\"Regular\",\"itc_classification\":\"All Other ITC\",\"ineligibility_reason\":\"\",\"reconciliation_status\":\"\",\"itc_integrated_tax\":0,\"itc_central_tax\":0,\"itc_state_tax\":0,\"itc_cess_amount\":0,\"on_hold\":0,\"is_internal_supplier\":0,\"represents_company\":\"\",\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Invoice\",\"pricing_rules\":[],\"payment_schedule\":[{\"name\":\"rcp9714j5f\",\"owner\":\"Administrator\",\"creation\":\"2024-12-23 17:37:43.391127\",\"modified\":\"2024-12-23 17:37:43.391127\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"due_date\":\"2024-12-23\",\"invoice_portion\":100,\"discount\":0,\"payment_amount\":100000,\"outstanding\":100000,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":100000,\"parent\":\"PINV-24-00022\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Payment Schedule\"}],\"supplied_items\":[],\"tax_withheld_vouchers\":[],\"advances\":[],\"advance_tax\":[],\"taxes\":[{\"name\":\"hrs9914qn1\",\"owner\":\"Administrator\",\"creation\":\"2024-12-23 17:37:43.389601\",\"modified\":\"2024-12-23 17:37:43.389601\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"category\":\"Total\",\"add_deduct_tax\":\"Deduct\",\"charge_type\":\"Actual\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"account_head\":\"TDS Payable - PP Ltd\",\"description\":\"Payment to Contractors (Single / Aggregate)\",\"is_tax_withholding_account\":1,\"rate\":0,\"cost_center\":\"\",\"tax_amount\":2000,\"tax_amount_after_discount_amount\":2000,\"total\":98000,\"base_tax_amount\":2000,\"base_total\":98000,\"base_tax_amount_after_discount_amount\":2000,\"item_wise_tax_detail\":\"{\\\"CPU\\\":[0.0,2000.0]}\",\"parent\":\"PINV-24-00022\",\"parentfield\":\"taxes\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Purchase Taxes and Charges\"}],\"items\":[{\"name\":\"ucds2jq8qf\",\"owner\":\"Administrator\",\"creation\":\"2024-12-23 17:37:43.178529\",\"modified\":\"2024-12-23 17:37:43.178529\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"item_code\":\"CPU\",\"item_name\":\"CPU\",\"description\":\"CPU\",\"is_ineligible_for_itc\":0,\"item_group\":\"_Test Item Group\",\"image\":\"\",\"received_qty\":0,\"qty\":4,\"rejected_qty\":0,\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_uom\":\"Nos\",\"stock_qty\":4,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":25000,\"amount\":100000,\"gst_treatment\":\"Nil-Rated\",\"base_rate\":25000,\"base_amount\":100000,\"pricing_rules\":\"\",\"stock_uom_rate\":25000,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":25000,\"net_amount\":100000,\"base_net_rate\":25000,\"base_net_amount\":100000,\"taxable_value\":0,\"igst_rate\":0,\"cgst_rate\":0,\"sgst_rate\":0,\"cess_rate\":0,\"cess_non_advol_rate\":0,\"igst_amount\":0,\"cgst_amount\":0,\"sgst_amount\":0,\"cess_amount\":0,\"cess_non_advol_amount\":0,\"valuation_rate\":25000,\"sales_incoming_rate\":0,\"item_tax_amount\":0,\"landed_cost_voucher_amount\":0,\"rm_supp_cost\":0,\"has_batch_no\":0,\"has_serial_no\":0,\"use_serial_batch_fields\":1,\"expense_account\":\"Stock Received But Not Billed - PP Ltd\",\"is_fixed_asset\":0,\"enable_deferred_expense\":0,\"allow_zero_valuation_rate\":0,\"item_tax_rate\":\"{}\",\"include_exploded_items\":0,\"weight_per_unit\":0,\"total_weight\":0,\"cost_center\":\"\",\"page_break\":0,\"parent\":\"PINV-24-00022\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Invoice\",\"doctype\":\"Purchase Invoice Item\"}],\"__onload\":{\"make_payment_via_journal_entry\":0,\"backflush_based_on\":\"BOM\",\"supplier_tds\":\"TDS - 194C - Company\"},\"__last_sync_on\":\"2024-12-23T12:24:35.482Z\"}",
		"method": "set_advances"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedFunction",
	"_exc_source": "india_compliance (app)",
	"_debug_messages": "[\"Error in query:\\noperator does not exist: character varying = boolean\\nLINE 1: ...tors - PP Ltd','Creditors - PP Ltd') OR (\\\"paid_to\\\"=true AND ...\\n                                                             ^\\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\\n\"]"
}
```

**Comment by Priya-Sonar** [comment]
@aasif-patel Please find the tracebook above.
Do let me know if you need anything else.

**Comment by tinadn** [comment]
This issue is linked with https://github.com/8848digital/erpnext/issues/891
So closing this issue.
