### ISSUE TITLE
zero-length delimited identifier at or near """"

### ISSUE THREAD

**Issue by ksagar8848** [8848digital/india_compliance#8]
### Information about bug

 test_gstr_3b_report (india_compliance.gst_india.doctype.gstr_3b_report.test_gstr_3b_report.TestGSTR3BReport.test_gstr_3b_report)

### Version

Frappe-v-15
Erpnex-v-15

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/test_gstr_3b_report.py", line 64, in test_gstr_3b_report
    ).insert()
      ^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in insert
    self.run_before_save_methods()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 36, in validate
    self.get_data()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 83, in get_data
    raise e
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 55, in get_data
    itc_details = self.get_itc_details()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/gstr_3b_report/gstr_3b_report.py", line 231, in get_itc_details
    itc_amounts = frappe.db.sql(
                  ^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: zero-length delimited identifier at or near """"
LINE 8: ...           and company_gstin != coalesce(supplier_gstin, "")
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by tinadn** [comment]
Resolved. Hence closing.
