### ISSUE TITLE
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date

### ISSUE THREAD

**Issue by ksagar8848** [8848digital/india_compliance#9]
### Information about bug

test_purchase_reconciliation_tool (india_compliance.gst_india.doctype.purchase_reconciliation_tool.test_purchase_reconciliation_tool.TestPurchaseReconciliationTool.test_purchase_reconciliation_tool)

### Version

Frappe-v-15
Erpnex-v-15

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/test_purchase_reconciliation_tool.py", line 95, in test_purchase_reconciliation_tool
    purchase_reconciliation_tool.save(ignore_permissions=True)
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 342, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 378, in _save
    self.run_before_save_methods()
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1103, in run_before_save_methods
    self.run_method("validate")
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/purchase_reconciliation_tool.py", line 88, in validate
    _Reconciler.reconcile(row["original"], row["amended"])
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 754, in reconcile
    purchases = self.get_unmatched_purchase_or_bill_of_entry(category)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 743, in get_unmatched_purchase_or_bill_of_entry
    return self.get_unmatched_purchase(category)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 700, in get_unmatched_purchase
    ).get_unmatched(category)
      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/__init__.py", line 399, in get_unmatched
    data = query.run(as_dict=True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/database/postgres/database.py", line 326, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/karunasagarravangave/plsbench/frappe-bench/apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: ""
LINE 1: ...E WHEN coalesce("tabPurchase Invoice"."bill_date",'')='' THE...
                                                             ^
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pallavi238848** [comment]
@tinadn , pls check is it fixed or not?

**Comment by aasif-patel** [comment]
@pallavi238848  getting another error 


ubuntu@ip-172-31-22-113:~/frappe-bench/sites$ bench run-tests --doctype "Purchase Reconciliation Tool" --test test_purchase_reconciliation_tool
E
======================================================================
ERROR: setUpClass (india_compliance.gst_india.doctype.purchase_reconciliation_tool.test_purchase_reconciliation_tool.TestPurchaseReconciliationTool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/india_compliance/india_compliance/gst_india/doctype/purchase_reconciliation_tool/test_purchase_reconciliation_tool.py", line 60, in setUpClass
    fiscal_year.update(
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 298, in insert
    self.run_before_save_methods()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1106, in run_before_save_methods
    self.run_method("validate")
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 977, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1337, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1319, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 974, in fn
    return method_object(*args, **kwargs)
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/fiscal_year/fiscal_year.py", line 34, in validate
    self.validate_overlap()
  File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/doctype/fiscal_year/fiscal_year.py", line 110, in validate_overlap
    frappe.throw(
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 632, in throw
    msgprint(
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 597, in msgprint
    _raise_exception()
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 548, in _raise_exception
    raise exc
frappe.exceptions.NameError: Year start date or end date is overlapping with _Test Short Fiscal Year 2024. To avoid please set company

----------------------------------------------------------------------
Ran 0 tests in 0.148s

FAILED (errors=1)

**Comment by pallavi238848** [comment]
Hi @ksagar8848 , pls check the issue added in the comments and try to resolve/fix it.

**Comment by anandk-spyke-o1** [comment]
@ksagar8848 
Today when I tested I got some another issue on server related to Fiscal Year 
frappe.exceptions.NameError: Year start date or end date is overlapping with _Test Short Fiscal Year 2024. To avoid please set company
Please fix this issue on priority as it is failing multiple test cases.
